repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: ['--select=B,C,E,F,W,T4,B9', '--max-complexity=18', '--max-line-length=79', '--ignore=E722,E203,E501,W503,F405']
      exclude: '.*\/migrations\/.*'